pipeline:
  name: Build Sample-Demo
  identifier: Build_Cager2808_Sample_Demo_1716918805684
  projectIdentifier: Demo_angular
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: angular cli
                  identifier: angular_cli
                  spec:
                    shell: Sh
                    command: npm install -g @angular/cli
              - step:
                  type: Run
                  name: version check
                  identifier: version_check
                  spec:
                    shell: Sh
                    command: ng v
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1698735122136
        repoName: Cager2808/Sample-Demo
        build: <+input>
